on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

    paths:
      - ".github/workflows/docker-alpine.yml"
      - "*.alpine.test.yml"
      - "alpine/**"

  # Run tests for any PRs.
  pull_request:

  # Triggered every day.
  schedule:
    - cron: "0 0 * * *"

env:
  REGISTRY: docker.io
  REGISTRY_USERNAME: ${{ secrets.DOCKER_IO_USERNAME }}
  REGISTRY_PASSWORD: ${{ secrets.DOCKER_IO_PASSWORD }}

jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        env:
          COMPOSE_FILE: docker-compose.openjdk.test.yml
        run: |
          sudo curl -sL "https://github.com/docker/compose/releases/download/1.25.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          if [ -f $COMPOSE_FILE ]; then
            docker-compose build --parallel
          fi

  push-glibc:
    # Ensure test job passes before pushing image.
    needs: test

    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'schedule'

    steps:
      - uses: actions/checkout@v2

      - name: Build the Docker image
        env:
          FILE_NAME: alpine/glibc.Dockerfile
          IMAGE_NAME: alpine:glibc
        run: docker build ./alpine --file $FILE_NAME
          --tag $IMAGE_NAME

      - name: Log into registry
        run: echo "${{ secrets.DOCKER_IO_PASSWORD }}" |
          docker login $REGISTRY -u ${{ secrets.DOCKER_IO_USERNAME }} --password-stdin

      - name: Push image
        env:
          IMAGE_NAME: alpine:glibc
        run: |
          IMAGE_ID=$REGISTRY/${{ secrets.DOCKER_IO_USERNAME }}/$IMAGE_NAME
          docker tag $IMAGE_NAME $IMAGE_ID
          docker push $IMAGE_ID

  push-jdk:
    # Ensure push-glibc job passes before pushing image.
    needs: push-glibc

    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'schedule'

    strategy:
      matrix:
        version: [6, 11]
        feature: [jdk, jre]

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - name: Build the Docker image
        env:
          FILE_NAME: alpine/${{ matrix.feature }}${{ matrix.version }}.Dockerfile
          IMAGE_NAME: alpine:${{ matrix.feature }}${{ matrix.version }}
        run: docker build ./alpine --file $FILE_NAME
          --tag $IMAGE_NAME

      - name: Log into registry
        run: echo "${{ secrets.DOCKER_IO_PASSWORD }}" |
          docker login $REGISTRY -u ${{ secrets.DOCKER_IO_USERNAME }} --password-stdin

      - name: Push image
        env:
          IMAGE_NAME: alpine:${{ matrix.feature }}${{ matrix.version }}
        run: |
          IMAGE_ID=$REGISTRY/${{ secrets.DOCKER_IO_USERNAME }}/$IMAGE_NAME
          docker tag $IMAGE_NAME $IMAGE_ID
          docker push $IMAGE_ID
